pull_request_rules:
  - name: automatic merge for develop raised by dependabot with label dependencies
    conditions:
      - base=develop
      - label=dependencies
      - conflict=false
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge