pull_request_rules:
  - name: automatic merge for develop raised by dependabot with label dependencies
    conditions:
      - base=develop
      - label=dependencies
      - status-success=continuous-integration/travis-ci/pr
      - -conflict
    actions:
      merge:
        method: merge